# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
stylua = "JohnnyMorganz/stylua@0.19.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.25.0"
